language: rust
sudo: false
os: linux
dist: trusty

rust:
  - nightly
  - beta
  - stable
  - 1.31.0

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never

env:
  global:
    - RUST_BACKTRACE=full

script:
  - cargo build --verbose
  - cargo doc   --verbose --no-deps

  - cargo test  --verbose
  - cargo test  --verbose --features 'serde'
  - cargo test  --verbose --features 'with_serde'

  - test "$TRAVIS_RUST_VERSION" != "nightly" ||
    cargo bench --verbose --features 'bench_it'

  - test "$TRAVIS_RUST_VERSION" != "nightly" ||
    cargo run   --verbose --features 'flame_it' --example 'flame_udhr'
